#ifndef PRAHARI_CONFIG_H
#define PRAHARI_CONFIG_H
#define PRAHARI_SAMPLE_RATE     16000
#define PRAHARI_SAMPLE_BITS     16
#define PRAHARI_WIN_SAMPLES     480
#define PRAHARI_HOP_SAMPLES     160
#define PRAHARI_FFT_SIZE        512
#define PRAHARI_MEL_BINS        40
#define PRAHARI_MEL_FMIN_HZ     20.0f
#define PRAHARI_MEL_FMAX_HZ     7600.0f
#define PRAHARI_LOG_EPSILON     1e-6f
#define PRAHARI_CTX_FRAMES      98
#define PRAHARI_FEATURE_COUNT   (PRAHARI_MEL_BINS * PRAHARI_CTX_FRAMES)
#define PRAHARI_LOGMEL_MIN     (-14.0f)
#define PRAHARI_LOGMEL_MAX     ( 6.5f)
#define PRAHARI_FEAT_SCALE      0.0803922f
#define PRAHARI_FEAT_ZERO_POINT 46
#define PRAHARI_SMOOTH_FRAMES   25
#define PRAHARI_REFRACTORY_MS   1500
#define PRAHARI_RAM_BUDGET_BYTES  (256 * 1024)
#define PRAHARI_KEYWORD         "prahari"
#define PRAHARI_NUM_CLASSES     2

#endif
