[platformio]
core_dir = C:/pio

[env:xiao_esp32s3]
platform      = espressif32
board         = seeed_xiao_esp32s3
framework     = arduino, espidf

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

monitor_dtr = 0
monitor_rts = 0

board_build.partitions = partitions.csv

build_flags =
    -I firmware/core
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
