import os, csv, json
import numpy as np
import tensorflow as tf
import prahari_config as cfg
from logmel import log_mel, load_wav_int16, quantise

TTS   = os.path.join("..", "tools", "dataset_tts")
NEG   = os.path.join("..", "tools", "dataset_neg")
TFLITE = os.path.join("artifacts", "prahari_int8.tflite")
OUT   = os.path.join("..", "firmware", "core", "prahari_test_clip.h")


def carray(name, pcm):
    out = [f"static const int16_t {name}[{len(pcm)}] = {{"]
    for i in range(0, len(pcm), 16):
        out.append("  " + ", ".join(str(int(v)) for v in pcm[i:i + 16]) + ",")
    out.append("};")
    return "\n".join(out)


def main():
    interp = tf.lite.Interpreter(model_path=TFLITE)
    interp.allocate_tensors()
    inp, out = interp.get_input_details()[0], interp.get_output_details()[0]
    s_in, z_in = inp["quantization"]
    s_out, z_out = out["quantization"]

    aff = {}
    aff_path = os.path.join("artifacts", "input_affine.json")
    if os.path.exists(aff_path):
        aff = json.load(open(aff_path))
    eff_scale = aff.get("eff_scale", s_in)
    eff_zp    = aff.get("eff_zp", float(z_in))
    eff_fill  = aff.get("eff_fill", int(z_in))
    folded    = bool(aff.get("folded", False))
    print(f"input BatchNorm : {'folded into the device constants' if folded else 'still in the graph'}")

    def score(pcm):
        lm = log_mel(pcm)[:cfg.CTX_FRAMES]
        q = np.clip(np.round(lm / eff_scale + eff_zp), -128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], q.reshape(1, cfg.CTX_FRAMES, cfg.MEL_BINS, 1))
        interp.invoke()
        raw = int(np.ravel(interp.get_tensor(out["index"]))[0])
        return (raw - z_out) * s_out, raw

    rows = list(csv.DictReader(open(os.path.join(TTS, "manifest.csv"), encoding="utf-8")))
    best_p, best_s = None, -1
    for r in [x for x in rows if x["label"] == "positive"][:40]:
        p = os.path.join(TTS, r["file"].replace("/", os.sep))
        if not os.path.exists(p):
            continue
        s, _ = score(load_wav_int16(p))
        if s > best_s:
            best_s, best_p = s, (p, r["file"], r["voice_name"], r["text"])

    neg_path = None
    np_man = os.path.join(NEG, "manifest.csv")
    if os.path.exists(np_man):
        for r in csv.DictReader(open(np_man, encoding="utf-8")):
            if r["kind"] == "speech":
                cand = os.path.join(NEG, r["file"].replace("/", os.sep))
                if os.path.exists(cand):
                    neg_path = (cand, r["file"], r["speaker"], "speech")
                    break

    pos_pcm = load_wav_int16(best_p[0])[:cfg.SAMPLE_RATE]
    pos_s, pos_raw = score(pos_pcm)
    neg_pcm = load_wav_int16(neg_path[0])[:cfg.SAMPLE_RATE]
    neg_s, neg_raw = score(neg_pcm)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(f"""/* =====================================================================
 *  PRAHARI - known clips for on-device verification
 *  GENERATED by training/gen_test_clip.py - DO NOT EDIT.
 *
 *  The device must reproduce these scores. They come from the int8
 *  TFLite model, which is exactly what runs on the board - so any
 *  disagreement is a real bug in the C chain, not a float/int8
 *  difference.
 *
 *  positive : {best_p[1]}  voice "{best_p[2]}"  text "{best_p[3]}"
 *  negative : {neg_path[1]}  speaker {neg_path[2]}
 * ===================================================================== */
#ifndef PRAHARI_TEST_CLIP_H
#define PRAHARI_TEST_CLIP_H

#include <stdint.h>

#define PRAHARI_TEST_CLIP_LEN {len(pos_pcm)}

/* Expected model output. int8 raw, and the dequantised score in [0,1]. */
#define PRAHARI_EXPECT_POS_RAW   {pos_raw}
#define PRAHARI_EXPECT_POS_SCORE {pos_s:.6f}f
#define PRAHARI_EXPECT_NEG_RAW   {neg_raw}
#define PRAHARI_EXPECT_NEG_SCORE {neg_s:.6f}f

/* Model input quantisation. The device must use THESE, not the constants
 * in prahari_config.h - the model file is the source of truth for what
 * the network expects.
 *
 * IN_SCALE and IN_ZP have the input BatchNorm folded into them, so the
 * device computes  round(mel/IN_SCALE + IN_ZP)  and gets exactly what
 * round((A*mel + B)/s_in + z_in) would have given - same one multiply and
 * one add as before, but the network is two operators shorter.
 *
 * IN_ZP is a FLOAT and is generally not a whole number, so round after
 * adding it. IN_FILL is its integer form, for the memset that clears the
 * feature history.  folded = {folded} */
#define PRAHARI_MODEL_IN_SCALE  {eff_scale:.9f}f
#define PRAHARI_MODEL_IN_ZP     {eff_zp:.6f}f
#define PRAHARI_MODEL_IN_FILL   {eff_fill}
#define PRAHARI_MODEL_OUT_SCALE {s_out:.9f}f
#define PRAHARI_MODEL_OUT_ZP    {z_out}

{carray("prahari_clip_positive", pos_pcm)}

{carray("prahari_clip_negative", neg_pcm)}

#endif /* PRAHARI_TEST_CLIP_H */
""")

    print(f"wrote {OUT}")
    print(f"  positive clip : {best_p[1]}  ({best_p[2]}, '{best_p[3]}')")
    print(f"     raw {pos_raw:>5}   score {pos_s:.6f}")
    print(f"  negative clip : {neg_path[1]}")
    print(f"     raw {neg_raw:>5}   score {neg_s:.6f}")
    print(f"  model input   : scale {eff_scale:.9f}  zero_point {eff_zp:.6f}"
          f"  fill {eff_fill}")
    print(f"  (raw tflite   : scale {s_in:.9f}  zero_point {z_in})")
    print(f"  model output  : scale {s_out:.9f}  zero_point {z_out}")
    print(f"  flash cost    : {2*len(pos_pcm)*2/1024:.0f} KB for both clips")
    print("\nThe device must print these same scores.")


if __name__ == "__main__":
    main()
