import os
import numpy as np
import prahari_config as cfg
from logmel import get_filterbank, hann_periodic

OUT = os.path.join("..", "firmware", "core", "prahari_tables.h")


def fmt(a, per_line=8, prec=9):
    lines, buf = [], []
    for i, v in enumerate(a):
        t = f"{v:.{prec}g}"
        if "." not in t and "e" not in t and "E" not in t:
            t += ".0"
        buf.append(t + "f")
        if len(buf) == per_line:
            lines.append("    " + ", ".join(buf) + ",")
            buf = []
    if buf:
        lines.append("    " + ", ".join(buf) + ",")
    return "\n".join(lines)


def fmt_int(a, per_line=16):
    lines, buf = [], []
    for v in a:
        buf.append(str(int(v)))
        if len(buf) == per_line:
            lines.append("    " + ", ".join(buf) + ",")
            buf = []
    if buf:
        lines.append("    " + ", ".join(buf) + ",")
    return "\n".join(lines)


def main():
    fb = get_filterbank()
    win = hann_periodic(cfg.WIN_SAMPLES)

    starts, lens, weights = [], [], []
    for m in range(fb.shape[0]):
        nz = np.nonzero(fb[m])[0]
        if len(nz) == 0:
            starts.append(0); lens.append(0); continue
        s, e = int(nz[0]), int(nz[-1]) + 1
        starts.append(s); lens.append(e - s)
        weights.extend(fb[m, s:e].tolist())

    offs, acc = [], 0
    for L in lens:
        offs.append(acc); acc += L
    nnz = acc

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(f"""/* =====================================================================
 *  PRAHARI - constant tables
 *  GENERATED by training/gen_c_tables.py - DO NOT EDIT BY HAND.
 *  Regenerate whenever logmel.py or prahari_config.py changes.
 *
 *  These live in flash and cost no RAM.
 * ===================================================================== */
#ifndef PRAHARI_TABLES_H
#define PRAHARI_TABLES_H

#include <stdint.h>
#include "prahari_config.h"

#define PRAHARI_MEL_NNZ {nnz}
#define PRAHARI_FFT_BINS {cfg.FFT_SIZE // 2 + 1}

/* Hann window, periodic: 0.5 - 0.5*cos(2*pi*n/N) */
static const float prahari_hann[PRAHARI_WIN_SAMPLES] = {{
{fmt(win)}
}};

/* Sparse mel filterbank.
 * mel bin m covers FFT bins [start[m], start[m]+len[m]) with weights
 * at w[off[m] ...]. Non-zero weights: {nnz} of {fb.size}. */
static const uint16_t prahari_mel_start[PRAHARI_MEL_BINS] = {{
{fmt_int(starts)}
}};
static const uint16_t prahari_mel_len[PRAHARI_MEL_BINS] = {{
{fmt_int(lens)}
}};
static const uint16_t prahari_mel_off[PRAHARI_MEL_BINS] = {{
{fmt_int(offs)}
}};
static const float prahari_mel_w[PRAHARI_MEL_NNZ] = {{
{fmt(weights)}
}};

#endif /* PRAHARI_TABLES_H */
""")

    dense = fb.size * 4
    sparse = nnz * 4 + 3 * cfg.MEL_BINS * 2
    print(f"wrote {OUT}")
    print(f"  hann window   : {cfg.WIN_SAMPLES} floats  ({cfg.WIN_SAMPLES*4/1024:.1f} KB)")
    print(f"  mel non-zeros : {nnz} of {fb.size}")
    print(f"  dense would be: {dense/1024:.1f} KB")
    print(f"  sparse is     : {sparse/1024:.1f} KB   ({dense/sparse:.1f}x smaller)")
    print(f"  total flash   : {(sparse + cfg.WIN_SAMPLES*4)/1024:.1f} KB")


if __name__ == "__main__":
    main()
